.pragma library

// GENERATED by tools/flea-themes-gen from vendor/strata-themes.toml. Do not edit; regenerate.
//
// Strata's bundled palette catalog, 95 themes (MIT, Copyright (c) 2026 LGSE Ltd., see
// vendor/LICENSE-strata; most entries are Tinted Base16 palettes it imported). The generator's
// header records which eight of Strata's fourteen tokens cross over and why.
//
// One line per theme, "id|Name|" then the eight colours in the order KEYS names them, because a
// line per colour is 760 lines against ui/js's 300-line hard cap (AGENTS.md "File budget").
var KEYS = ["background", "dark_background", "foreground", "accent", "red", "muted", "green", "cyan"]

var CATALOG = [
    "0x96f|0x96f|#1e1d1f|#262427|#fcfcfc|#a093e2|#ff8787|#a6a6a5|#bcdf59|#aee8f4",
    "3024|3024|#090300|#3a3432|#a5a2a2|#01a0e4|#db2d20|#807d7c|#01a252|#b5e4f4",
    "atelier-cave|Atelier Cave|#19171c|#26232a|#8b8792|#576ddb|#be4678|#7e7887|#2a9292|#398bc6",
    "atelier-cave-light|Atelier Cave Light|#efecf4|#e2dfe7|#585260|#576ddb|#be4678|#655f6d|#2a9292|#398bc6",
    "atelier-dune|Atelier Dune|#20201d|#292824|#a6a28c|#6684e1|#d73737|#999580|#60ac39|#1fad83",
    "atelier-dune-light|Atelier Dune Light|#fefbec|#e8e4cf|#6e6b5e|#6684e1|#d73737|#7d7a68|#60ac39|#1fad83",
    "atelier-forest|Atelier Forest|#1b1918|#2c2421|#a8a19f|#407ee7|#f22c40|#9c9491|#7b9726|#3d97b8",
    "atelier-forest-light|Atelier Forest Light|#f1efee|#e6e2e0|#68615e|#407ee7|#f22c40|#766e6b|#7b9726|#3d97b8",
    "atelier-heath|Atelier Heath|#1b181b|#292329|#ab9bab|#516aec|#ca402b|#9e8f9e|#918b3b|#159393",
    "atelier-heath-light|Atelier Heath Light|#f7f3f7|#d8cad8|#695d69|#516aec|#ca402b|#776977|#918b3b|#159393",
    "atelier-lakeside|Atelier Lakeside|#161b1d|#1f292e|#7ea2b4|#257fad|#d22d72|#7195a8|#568c3b|#2d8f6f",
    "atelier-lakeside-light|Atelier Lakeside Light|#ebf8ff|#c1e4f6|#516d7b|#257fad|#d22d72|#5a7b8c|#568c3b|#2d8f6f",
    "atelier-seaside|Atelier Seaside|#131513|#242924|#8ca68c|#3d62f5|#e6193c|#809980|#29a329|#1999b3",
    "atelier-seaside-light|Atelier Seaside Light|#f4fbf4|#cfe8cf|#5e6e5e|#3d62f5|#e6193c|#687d68|#29a329|#1999b3",
    "ayu-dark|Ayu Dark|#0b0e14|#131721|#e6e1cf|#59c2ff|#f07178|#bfbdb6|#aad94c|#95e6cb",
    "ayu-light|Ayu Light|#f8f9fa|#edeff1|#5c6166|#399ee6|#f07171|#8a9199|#6cbf49|#4cbf99",
    "ayu-mirage|Ayu Mirage|#1f2430|#242936|#cccac2|#73d0ff|#f28779|#707a8c|#d5ff80|#95e6cb",
    "azure-glow|Azure Glow|#03111e|#061a29|#b8dbe7|#2ccceb|#e5484d|#395a6d|#83d9aa|#e4d58a",
    "bright|Bright|#000000|#303030|#e0e0e0|#6fb3d2|#fb0120|#d0d0d0|#a1c659|#76c7b7",
    "catppuccin|Catppuccin|#1e1e2e|#242438|#cdd6f4|#f5c2e7|#e5484d|#7f849c|#a6e3a1|#94e2d5",
    "catppuccin-frappe|Catppuccin Frappe|#303446|#292c3c|#c6d0f5|#8caaee|#e78284|#626880|#a6d189|#81c8be",
    "catppuccin-latte|Catppuccin Latte|#eff1f5|#e6e9ef|#4c4f69|#1e66f5|#d20f39|#acb0be|#40a02b|#179299",
    "catppuccin-macchiato|Catppuccin Macchiato|#24273a|#1e2030|#cad3f5|#8aadf4|#ed8796|#5b6078|#a6da95|#8bd5ca",
    "catppuccin-mocha|Catppuccin Mocha|#1e1e2e|#181825|#cdd6f4|#89b4fa|#f38ba8|#585b70|#a6e3a1|#94e2d5",
    "chalk|Chalk|#151515|#202020|#d0d0d0|#6fc2ef|#fb9fb1|#b0b0b0|#acc267|#12cfc0",
    "classic-dark|Classic Dark|#151515|#202020|#d0d0d0|#6a9fb5|#ac4142|#b0b0b0|#90a959|#75b5aa",
    "classic-light|Classic Light|#f5f5f5|#e0e0e0|#303030|#6a9fb5|#ac4142|#505050|#90a959|#75b5aa",
    "cupertino|Cupertino|#ffffff|#c0c0c0|#404040|#0000ff|#c41a15|#808080|#007400|#318495",
    "darcula|Darcula|#2b2b2b|#323232|#a9b7c6|#9876aa|#4eade5|#a4a3a3|#6a8759|#629755",
    "decaf|Decaf|#2d2d2d|#393939|#cccccc|#90bee1|#ff7f7b|#b4b7b4|#beda78|#bed6ff",
    "dracula|Dracula|#282a36|#21222c|#f8f8f2|#bd93f9|#ff5555|#9ea8c7|#50fa7b|#8be9fd",
    "eighties|Eighties|#2d2d2d|#393939|#d3d0c8|#6699cc|#f2777a|#a09f93|#99cc99|#66cccc",
    "embers|Embers|#16130f|#2c2620|#a39a90|#6d5782|#826d57|#8a8075|#57826d|#576d82",
    "espresso|Espresso|#2d2d2d|#393939|#cccccc|#6c99bb|#d25252|#b4b7b4|#a5c261|#bed6ff",
    "everforest|Everforest|#2d353b|#343f44|#d3c6aa|#a7c080|#e5484d|#859289|#a7c080|#83c092",
    "everforest-dark-hard|Everforest Dark Hard|#272e33|#2e383c|#d3c6aa|#7fbbb3|#e67e80|#9da9a0|#a7c080|#83c092",
    "everforest-dark-soft|Everforest Dark Soft|#333c43|#3a464c|#d3c6aa|#7fbbb3|#e67e80|#9da9a0|#a7c080|#83c092",
    "everforest-light-hard|Everforest Light (Hard)|#fffbef|#f8f5e4|#5c6a72|#3a94c5|#f85552|#829181|#8da101|#35a77c",
    "everforest-light-medium|Everforest Light (Soft)|#fdf6e3|#f4f0d9|#5c6a72|#3a94c5|#f85552|#829181|#8da101|#35a77c",
    "flexoki-dark|Flexoki Dark|#100f0f|#1c1b1a|#cecdc3|#4385be|#d14d41|#878580|#879a39|#3aa99f",
    "flexoki-light|Flexoki Light|#fffcf0|#f2f0e5|#403e3c|#205ea6|#af3029|#9f9d96|#66800b|#24837b",
    "github|Github|#ffffff|#f6f8fa|#424a53|#8250df|#953800|#6e7781|#0a3069|#116329",
    "github-dark|Github Dark|#0d1117|#161b22|#c9d1d9|#d2a8ff|#ffa657|#8b949e|#a5d6ff|#7ee787",
    "github-dark-dimmed|Github Dark Dimmed|#22272e|#2d333b|#adbac7|#dcbdfb|#f69d50|#768390|#96d0ff|#8ddb8c",
    "github-dark-high-contrast|Github Dark High Contrast|#0a0c10|#272b33|#f0f3f6|#dbb7ff|#ffb757|#bdc4cc|#addcff|#72f088",
    "github-light-high-contrast|Github Light High Contrast|#ffffff|#e7ecf0|#343b43|#622cbc|#702c00|#66707b|#032563|#024c1a",
    "google-dark|Google Dark|#1d1f21|#282a2e|#c5c8c6|#3971ed|#cc342b|#b4b7b4|#198844|#3971ed",
    "google-light|Google Light|#ffffff|#e0e0e0|#373b41|#3971ed|#cc342b|#969896|#198844|#3971ed",
    "gotham|Gotham|#0c1014|#11151c|#599cab|#195466|#c23127|#245361|#33859e|#2aa889",
    "grayscale-dark|Grayscale Dark|#101010|#252525|#b9b9b9|#686868|#7c7c7c|#ababab|#8e8e8e|#868686",
    "grayscale-light|Grayscale Light|#f7f7f7|#e3e3e3|#464646|#686868|#7c7c7c|#525252|#8e8e8e|#868686",
    "greenscreen|Green Screen|#001100|#003300|#00bb00|#009900|#007700|#009900|#00bb00|#005500",
    "gruvbox-dark-hard|Gruvbox Dark|#1d2021|#3c3836|#d5c4a1|#83a598|#fb4934|#bdae93|#b8bb26|#8ec07c",
    "gruvbox-light-hard|Gruvbox Light|#f9f5d7|#ebdbb2|#504945|#076678|#9d0006|#665c54|#79740e|#427b58",
    "gruvbox-material-dark-medium|Gruvbox Material Dark, Medium|#292828|#32302f|#ddc7a1|#7daea3|#ea6962|#bdae93|#a9b665|#89b482",
    "gruvbox-material-light-medium|Gruvbox Material Light, Medium|#fbf1c7|#f2e5bc|#654735|#45707a|#c14a4a|#665c54|#6c782e|#4c7a5d",
    "horizon-dark|Horizon Dark|#1c1e26|#232530|#cbced0|#df5273|#e93c58|#9da0a2|#efaf8e|#24a8b4",
    "horizon-light|Horizon Light|#fdf0ed|#fadad1|#403c3d|#da103f|#f7939b|#948c8a|#94e1b0|#dc3318",
    "irblack|IR Black|#000000|#242422|#b5b3aa|#96cbfe|#ff6c60|#918f88|#a8ff60|#c6c5fe",
    "kanagawa|Kanagawa|#1f1f28|#16161d|#dcd7ba|#7e9cd8|#c34043|#727169|#76946a|#6a9589",
    "kanagawa-dragon|Kanagawa Dragon|#181616|#282727|#c5c9c5|#8ba4b0|#c4746e|#737c73|#8a9a7b|#8ea4a2",
    "material-darker|Material Darker|#212121|#303030|#eeffff|#82aaff|#f07178|#b2ccd6|#c3e88d|#89ddff",
    "material-lighter|Material Lighter|#fafafa|#e7eaec|#80cbc4|#6182b8|#ff5370|#8796b0|#91b859|#39adb5",
    "material-palenight|Material Palenight|#292d3e|#444267|#959dcb|#82aaff|#f07178|#8796b0|#c3e88d|#89ddff",
    "material-vivid|Material Vivid|#202124|#27292c|#80868b|#2196f3|#f44336|#676c71|#00e676|#00bcd4",
    "monokai|Monokai|#272822|#383830|#f8f8f2|#66d9ef|#f92672|#a59f85|#a6e22e|#a1efe4",
    "moonlight|Moonlight|#212337|#403c64|#a3ace1|#40ffff|#ff5370|#a1abe0|#2df4c0|#04d1f9",
    "neovim-dark|Neovim Dark|#14161b|#07080d|#e0e2ea|#a6dbff|#ffc0b9|#c4c6cd|#b3f6c0|#8cf8f7",
    "neovim-light|Neovim Light|#e0e2ea|#eef1f8|#14161b|#004c73|#590008|#2c2e33|#005523|#007373",
    "nord|Nord|#2e3440|#3b4252|#e5e9f0|#81a1c1|#bf616a|#d8dee9|#a3be8c|#88c0d0",
    "nord-light|Nord Light|#e5e9f0|#c2d0e7|#2e3440|#3b6ea8|#99324b|#60728c|#4f894c|#398eac",
    "oceanicnext|OceanicNext|#1b2b34|#343d46|#c0c5ce|#6699cc|#ec5f67|#a7adba|#99c794|#5fb3b3",
    "omarchy-light|Omarchy Light|#edf2f6|#f8fafc|#1f2d38|#007f9d|#e5484d|#526674|#287344|#806000",
    "one-light|One Light|#fafafa|#f0f0f1|#383a42|#4078f2|#ca1243|#696c77|#50a14f|#0184bc",
    "onedark-dark|OneDark Dark|#000000|#1c1f24|#abb2bf|#61afef|#ef596f|#565c64|#89ca78|#2bbac5",
    "outrun-dark|Outrun Dark|#00002a|#20204a|#d0d0fa|#66b0ff|#ff4242|#b0b0da|#59f176|#0ef0f0",
    "oxocarbon-dark|Oxocarbon Dark|#161616|#262626|#f2f4f8|#33b1ff|#ee5396|#dde1e6|#42be65|#3ddbd9",
    "oxocarbon-light|Oxocarbon Light|#f2f4f8|#dde1e6|#525f70|#0f62fe|#ff7eb6|#68788d|#42be65|#673ab7",
    "papercolor-dark|PaperColor Dark|#1c1c1c|#363636|#9e9e9e|#5fafd7|#ff5faf|#808080|#5faf5f|#00afaf",
    "papercolor-light|PaperColor Light|#eeeeee|#c4c4c4|#5e5e5e|#005f87|#d70000|#6b6b6b|#008700|#0087af",
    "railscasts|Railscasts|#2b2b2b|#272935|#e6e1dc|#6d9cbe|#da4939|#d4cfc9|#a5c261|#519f50",
    "rose-pine|Rosé Pine|#191724|#1f1d2e|#e0def4|#ebbcba|#e5484d|#817c9c|#31748f|#9ccfd8",
    "rose-pine-dawn|Rosé Pine Dawn|#faf4ed|#fffaf3|#575279|#907aa9|#b4637a|#797593|#286983|#56949f",
    "rose-pine-moon|Rosé Pine Moon|#232136|#2a273f|#e0def4|#c4a7e7|#eb6f92|#908caa|#3e8fb0|#9ccfd8",
    "snazzy|Snazzy|#282a36|#34353e|#e2e4e5|#57c7ff|#ff5c57|#a5a5a9|#5af78e|#9aedfe",
    "solarized-dark|Solarized Dark|#002b36|#073642|#93a1a1|#268bd2|#dc322f|#839496|#859900|#2aa198",
    "solarized-light|Solarized Light|#fdf6e3|#eee8d5|#586e75|#268bd2|#dc322f|#657b83|#859900|#2aa198",
    "spacemacs|Spacemacs|#1f2022|#282828|#a3a3a3|#4f97d7|#f2241f|#b8b8b8|#67b11d|#2d9574",
    "tokyo-night|Tokyo Night|#16161e|#1f2335|#c0caf5|#7aa2f7|#e5484d|#737aa2|#9ece6a|#b4f9f8",
    "tokyo-night-moon|Tokyo Night Moon|#222436|#1e2030|#828bb8|#82aaff|#ff757f|#636da6|#c3e88d|#86e1fc",
    "tokyo-night-storm|Tokyo Night Storm|#24283b|#16161e|#a9b1d6|#2ac3de|#c0caf5|#787c99|#9ece6a|#b4f9f8",
    "tomorrow|Tomorrow|#ffffff|#e0e0e0|#373b41|#4271ae|#c82829|#969896|#718c00|#3e999f",
    "tomorrow-night|Tomorrow Night|#1d1f21|#282a2e|#c5c8c6|#81a2be|#cc6666|#b4b7b4|#b5bd68|#8abeb7",
    "twilight|Twilight|#1e1e1e|#323537|#a7a7a7|#7587a6|#cf6a4c|#838184|#8f9d6a|#afc4db",
    "zenburn|Zenburn|#383838|#404040|#dcdccc|#7cb8bb|#dca3a3|#808080|#5f7f5f|#93e0e3"
]

// "omarchy" is not in CATALOG: it is the absence of a catalog choice, and the default. ui/Theme.qml
// reads the desktop's own colors.toml for it, which is what Flea has always done and what the
// README promises; a catalog id only ever replaces the body that read comes back with.
var FOLLOW = "omarchy"

var INDEX = null

function index() {
    if (INDEX)
        return INDEX
    INDEX = {}
    for (var i = 0; i < CATALOG.length; i++)
        INDEX[CATALOG[i].split("|")[0]] = CATALOG[i]
    return INDEX
}

// Every theme as {id, name}, in the catalog's own order, which is Strata's: id-sorted.
function entries() {
    var out = []
    for (var i = 0; i < CATALOG.length; i++) {
        var fields = CATALOG[i].split("|")
        out.push({ id: fields[0], name: fields[1] })
    }
    return out
}

function has(id) {
    return index()[String(id)] !== undefined
}

// The display name, or "" for an id no catalog entry carries.
function nameOf(id) {
    var row = index()[String(id)]
    return row ? row.split("|")[1] : ""
}

// The eight colours of one theme as {key: hex}, or null for an id the catalog does not carry. A
// caller that gets null follows Omarchy, which is what a stored id from a newer build resolves to.
function colorsOf(id) {
    var row = index()[String(id)]
    if (!row)
        return null
    var fields = row.split("|")
    var out = {}
    for (var i = 0; i < KEYS.length; i++)
        out[KEYS[i]] = fields[i + 2]
    return out
}

// One theme as colors.toml text, which is the one thing ui/Theme.qml's applyColors takes. A
// catalog palette therefore runs the same parse, the same WCAG lifts and the same eight
// assignments an Omarchy theme runs, rather than a second path beside them.
function paletteBody(id) {
    var colors = colorsOf(id)
    if (!colors)
        return ""
    var lines = []
    for (var i = 0; i < KEYS.length; i++)
        lines.push(KEYS[i] + ' = "' + colors[KEYS[i]] + '"')
    return lines.join("\n") + "\n"
}

// What a stored value means: "" and "omarchy" and an id this build's catalog lost all follow the
// desktop, and only an id the catalog carries selects a palette. One place decides it, so no
// surface can disagree with another about whether a window is following.
function following(id) {
    return !has(id)
}

function resolve(id) {
    return has(id) ? String(id) : FOLLOW
}
